name: WoT
markdown: kramdown

# uncomment if in root
#url: "https://w3c.github.com"
#baseurl: "/wot-marketing"
url: "https://www.w3.org"
baseurl: "/WoT"

navigation:
 - title: Standards
   subnavigation:
   - title: Working Group
     url: wg/
   - title: Interest Group
     url: ig/
 - title: Community
   url: cg/
 - title: Activities
   subnavigation:
   - title: General
     url: activities/general/
   - title: Architecture
     url: activities/tf-architecture/
   - title: Thing Description
     url: activities/tf-td/
   - title: Discovery
     url: activities/tf-discovery/
   - title: Security
     url: activities/tf-security/
   - title: Scripting API
     url: activities/tf-scripting/
   - title: Use Cases
     url: activities/tf-usecases/
 - title: Developers
   url: developers/
 - title: More
   subnavigation:
   - title: Documentation
     url: documentation/
   - title: Videos
     url: videos/
#   - title: Getting Started
#     url: getting-started/
#   - title: Calls and Meetings
#     url: https://www.w3.org/WoT/IG/wiki/
